pipeline{
    agent any 
    stages{
        stage('init'){
            steps{
                sh 'terraform init -no-color'
            }
        }
    }
    stage('validate'){
            steps{
                sh 'terraform init -no-color'
            }
        }
    }
     stage('format'){
            steps{
                sh 'terraform init -no-color'
            }
        }
    }
     stage('plan'){
            steps{
                sh 'terraform init -no-color'
            }
        }
    }
}